
DROP TABLE IF EXISTS cities CASCADE;

CREATE TABLE cities (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  heath_authority_name VARCHAR(255) REFERENCES health_authorities(name) ON DELETE CASCADE
  );